### ISSUE TITLE
the team color is not correct

### ISSUE THREAD

**Issue by tppqt** [Yousef-Nasr/Football-Analysis#1]
![330756826-07f24795-1ec7-4797-bf24-eb9652324010](https://github.com/Yousef-Nasr/Football-Analysis/assets/19279148/89aaa057-8928-4fbb-8cba-d8fddb57ea46)
I ran your project and found an issue with using k-means to differentiate team colors.The purple jerseys have been clustered with the white jerseys, I try center-box and foreground , but it [didn't] work.

**Comment by Yousef-Nasr** [comment]
you can check the new method using visual embedding with **(siglip model).**
